#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum class WINMODE { FULL, WIN };

	enum class RENDERGROUP { PRIORITY, NONBLEND, BLEND, UI, END };

	enum class STATE { RIGHT, UP, LOOK, POSITION, END };

	enum class ERESOURCE { SHADER, END };

	enum class MODELTYPE { NONANIM, ANIM, END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum FILEHEADERTYPE { FILEHEADER_MODEL, FILEHEADER_ANIMATION, END };

	enum CHUNCKTYPE { CHUNK_MESH = 1, CHUNK_MATERIAL, CHUNK_TEXTURE, CHUNK_SKELETON, CHUNK_ANIMATION};

	enum TEXTURETYPE {
		NONE = 0, DIFFUSE = 1, SPECULAR = 2, AMBIENT = 3, EMISSIVE = 4, HEIGHT = 5, NORMALS = 6, SHININESS = 7, OPACITY = 8, DISPLACEMENT = 9, LIGHTMAP = 10, REFLECTION = 11, BASE_COLOR = 12,
		NORMAL_CAMERA = 13, EMISSION_COLOR = 14, METALNESS = 15, DIFFUSE_ROUGHNESS = 16, AMBIENT_OCCLUSION = 17, UNKNOWN = 18, SHEEN = 19, CLEARCOAT = 20, TRANSMISSION = 21, MAYA_BASE = 22,
		MAYA_SPECULAR = 23, MAYA_SPECULAR_COLOR = 24, MAYA_SPECULAR_ROUGHNESS = 25, ANISOTROPY = 26, GLTF_METALLIC_ROUGHNESS = 27, TextureType_END
	};

	enum OBJECTTYPE { OBJECT_PLAYER, OBJECT_MONSTER, OBJECT_STATIC, OBJECT_CAMERA, OBJECT_TERRIAN, OBJECT_SKYBOX, OBEJCT_PART };

	enum COLLIDER { COLLIDER_AABB, COLLIDER_OBB, COLLIDER_SPHERE, COLLIDER_END };
	//// Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
	//enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	//enum INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };

	//enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	//enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	//enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };



}
#endif // Engine_Enum_h__
