#pragma once

#include <Windows.h>
#include <memory>
#include <process.h>


namespace Client
{
	static const unsigned int		g_iWinSizeX = { 1280 };
	static const unsigned int		g_iWinSizeY = { 720 };

	enum class LEVEL {LOADING, LOGO, GAMEPLAY, MAPEDITOR, END};
	enum class CAMERA {MAIN, SUB, NONE,PLAYER, END};
	enum class TEXTURETYPE {
		NONE = 0, DIFFUSE = 1, SPECULAR = 2, AMBIENT = 3, EMISSIVE = 4, HEIGHT = 5, NORMALS = 6, SHININESS = 7, OPACITY = 8, DISPLACEMENT = 9, LIGHTMAP = 10, REFLECTION = 11, BASE_COLOR = 12,
		NORMAL_CAMERA = 13, EMISSION_COLOR = 14, METALNESS = 15, DIFFUSE_ROUGHNESS = 16, AMBIENT_OCCLUSION = 17, UNKNOWN = 18, SHEEN = 19, CLEARCOAT = 20, TRANSMISSION = 21, MAYA_BASE = 22,
		MAYA_SPECULAR = 23, MAYA_SPECULAR_COLOR = 24, MAYA_SPECULAR_ROUGHNESS = 25, ANISOTROPY = 26, GLTF_METALLIC_ROUGHNESS = 27, MATERIAL_END
	};
	enum COLLIDER { COLLIDER_AABB, COLLIDER_OBB, COLLIDER_SPHERE, COLLIDER_END};
	enum OBJECTTYPE { OBJECT_PLAYER, OBJECT_MONSTER, OBJECT_STATIC, OBJECT_CAMERA, OBJECT_TERRIAN, OBJECT_SKYBOX, OBEJCT_PART, OBJECT_UI};



}

extern HWND			g_hWnd;
extern HINSTANCE	g_hInstance;

using namespace std;
using namespace Client;
